### PR TITLE
Create adjacency_list.cpp

### PR DESCRIPTION
**Pull request by sagardeepesh2**
Sir, please accept my PR as I come from an awfully rich background and want to experience mediocracy by using mediocracy
(P.S. my younger brother is an angel investor)

### CODE REVIEW

**Comment by Pushpit07** [comment]
Sir, invest in Dogecoin!

**Comment by sagardeepesh2** [comment]
I have Elon's son's phone number

**Comment by Pushpit07** [comment]
Naam kya hai uska?

**Comment by Yuvrajchandra** [comment]
image

**Comment by sagardeepesh2** [comment]
LA m rehta hun aane ni dete ghar wale

**Comment by Yuvrajchandra** [comment]
Angel Investor?
Bhaimya ye repo ki funding karwa dete to 🥺👉👈

**Pull request merged**
