### PR TITLE
Create_11_Modular_Multiplicative_Inverse.cpp

### PR DESCRIPTION
**Pull request by Shivamsingh-c17**
Create_11_Modular_Multiplicative_Inverse ....Please accept

### CODE REVIEW

**Comment by Yuvrajchandra** [comment]
You haven't used AI, Blockchain, AR/VR, Machine Learning, Big Data????
How were you able to write this code???

Well, Good Job.
Accepting this PR

**Comment by Pushpit07** [comment]
He made the whole process simplified sir

**Comment by Pushpit07** [comment]
Kudos @Shivamsingh-c17 !

**Comment by Yuvrajchandra** [comment]
Hi @Pushpit07 
We're sorry to inform you that you don't know PHP so we can't hire you!
"Start where you are. Use what you have. Do what you can."
Read more at https://www.brainyquote.com/topics/motivational-quotes
image

**Pull request merged**
