### PR TITLE
Convert Celsius To Fahrenheit

### PR DESCRIPTION
**Pull request by Pushpit07**
This helpful code written in the C++ programming language will make the task of converting temperature in Celsius to Fahrenheit really easy for users. I've given a lot of thought in creating this code and I think you will appreciate my hard work with all the comments I have put to make your task of reviewing easier. Please guide me as you've been doing all this time.

Looking forward to more such collaborations. And Happy Gandhi Jayanti, sir.

### CODE REVIEW

**Comment by Yuvrajchandra** [comment]
Bjarne Stroustrup would be so happy to see this code. I'm impressed by your hard work. Mark my words, your thoughts would take you to the places you can't even imagine. I'm damn sure you'll become the first GitHub Students Partner of Mars. See you on the other planet.

I'll be so happy to guide you. Pleamse send 2kg laddus. DON'T tell to anyone about this. Got it?

@here Naathu! See what's happening here!
BTW Happy Gandhi Jayanti!
image

**Comment by Pushpit07** [comment]
Bapu ki jai!

**Comment by Pushpit07** [comment]
Thank you for the positive response sir!

**Comment by Pushpit07** [comment]
Bapu ka aashirvaad bana rahe

**Comment by Yuvrajchandra** [comment]
@sagardeepesh2 OK Boomer!🙂

**Comment by Pushpit07** [comment]
You can take a look at Mr. Deepesh (@sagardeepesh2)
He is a total pedophile

**Comment by Pushpit07** [comment]
PDFfile*

**Comment by Yuvrajchandra** [comment]
image
Heemlo PDF file!

**Pull request merged**
